"""agregando fecha_inscripcion

Revision ID: ede01a48e494
Revises: 5b3a2dd2a055
Create Date: 2026-03-05 20:38:18.770222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ede01a48e494'
down_revision = '5b3a2dd2a055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])
        batch_op.drop_column('created_date')

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_alumno_curso', ['alumno_id', 'curso_id'])

    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('apellidos',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('matricula'))
        batch_op.drop_column('created_date')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_date', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('matricula'), ['matricula'], unique=True)
        batch_op.alter_column('apellidos',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('matricula',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_alumno_curso', type_='unique')
        batch_op.drop_column('fecha_inscripcion')
        batch_op.drop_column('id')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
